### ISSUE TITLE
App won't accept my CitiPower VEC CSVs

### ISSUE THREAD

**Issue by Datisit** [longzheng/ato-homeoffice-vec-electricity-calculator#1]
Hey there, 

Firstly, I saw you post this app on /r/Melbourne back in September and saved it for tax time now.
It looks great, but unfortunately I've not managed to get it to read my CSVs.

I've generated a Victorian Energy Compare CSV both from my reseller, Momentum, and my supplier, Citipower. 
I've confirmed that both the Momentum & CitiPower generated CSVs do work on the the VEC website.

However, this app will not accept them, giving this error:
"There was a problem processing the CSV. Please ensure this data is in the correct Victorian Energy Compare Data format."

Totally cool if you aren't interested to work on this anymore, but I thought I'd give it a go anyway.

Thanks

**Comment by longzheng** [comment]
I've learned that some retailers generate slightly different columns in the CSV so should be possible to tweak if you can provide me a copy of your CSV headers.

**Comment by Datisit** [comment]
Ah that would be brillaint, thanks!
Here are the files:
[6102583120_20200701_20210630_20210714142807_Momentum Energy_DETAILED.csv](https://github.com/longzheng/ato-homeoffice-vec-electricity-calculator/files/6819680/6102583120_20200701_20210630_20210714142807_Momentum.Energy_DETAILED.csv)
[61025831206_20200714_20210714_20210714160212_CITIPOWER_VECFORMAT.csv](https://github.com/longzheng/ato-homeoffice-vec-electricity-calculator/files/6819681/61025831206_20200714_20210714_20210714160212_CITIPOWER_VECFORMAT.csv)

**Comment by longzheng** [comment]
Sorry was a bit busy over the last 2 days and only just got a chance to have a look, this does look very different to the format used by United Energy.

I'm not quite sure yet how much work it'll be to add support for, I'll need to take a closer look on the weekend.

**Comment by Datisit** [comment]
Hey please don’t stress!

I’m really grateful for the help, but honestly please don’t feel you have to look with any urgency. 
Or if it seems too tricky, please don’t worry at all!

**Comment by longzheng** [comment]
I found someone documented the CitiPower CSV format here https://forums.whirlpool.net.au/thread/9q78vxv9#r44579465 seems pretty straight forward, I'll take a stab now.

**Comment by Datisit** [comment]
Ah amazing

**Comment by longzheng** [comment]
Added a dropdown to let you choose the CitiPower CSV format

![image](https://user-images.githubusercontent.com/484912/126026760-dcd218c2-b07a-4b13-ac7d-d06729dd0809.png)

**Comment by Datisit** [comment]
Thank you so much, I'm excited to check it out tomorrow!

**Comment by Datisit** [comment]
Hey again,

Thanks so much for helping me with this last year. 

Turns out the VEC format has changed again, at least according to Citipower/powercor. 

It’s now apparently the same as their ‘detailed report’:

“ From December 2021 - VEC Format has changed and now mimics the Detailed Report. This change was to meet an updated government data format which allows for more data to be captured now that the industry is moving to 5-minute interval data over the coming years.”

It’s totally okay if you’re not interested in this anymore, but I just thought I’d check to see how complex you think it would be to adjust for this new format?

Attached is an example file


Thanks,
Darcy

**Comment by longzheng** [comment]
@Datisit I don't think your example attachment came through. If you could maybe upload it directly to GitHub?

**Comment by Datisit** [comment]
Ah yep of course here ya go: 

[61025831206_20210724_20220724_20220725131354_CITIPOWER_VECFORMAT.csv](https://github.com/longzheng/ato-homeoffice-vec-electricity-calculator/files/9230884/61025831206_20210724_20220724_20220725131354_CITIPOWER_VECFORMAT.csv)

**Comment by longzheng** [comment]
@Datisit Does Citipower offer any other export format now?

**Comment by Datisit** [comment]
They offer three CSVs in total, the VEC Format, the Detailed report which is the same as the VEC Format now and also this summary report
[61025831206_20200805_20220804_20220805125659_CITIPOWER_SUMMARY.csv](https://github.com/longzheng/ato-homeoffice-vec-electricity-calculator/files/9264886/61025831206_20200805_20220804_20220805125659_CITIPOWER_SUMMARY.csv)
[61025831206_20200725_20220724_20220725131258_CITIPOWER_DETAILED.csv](https://github.com/longzheng/ato-homeoffice-vec-electricity-calculator/files/9264889/61025831206_20200725_20220724_20220725131258_CITIPOWER_DETAILED.csv)

**Comment by longzheng** [comment]
Sorry @Datisit , I had another look and the "detailed" report does have all the necessary interval consumption data, but it's in a AEMO NEM12 format that's very different to the United Energy one. 

It's not technically impossible but unfortunately I'm pretty busy these days so don't really have the time to add support for it.

**Comment by Datisit** [comment]
Hey that’s totally okay. 
I appreciate all the effort you’ve put in so far and for making such a useful tool for everyone. 

Thanks and good luck with all your work and projects!
